/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.FinancialAdvisorRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.LabOrganization;
import Business.Organization.Organization;
import Business.Organization.RetailOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.Create_Loan_Mortgage_Soc_WorkRequest;
import Business.WorkQueue.LabTestWorkRequest;
//import Business.WorkQueue.SocWorkRequest;
import Business.WorkQueue.WorkRequest;
import UserInterface.DoctorRole.DoctorWorkAreaJPanel;

import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
//import userinterface.CustomerRole.RequestLoanJPanel;
//import userinterface.RetailManagerRole.RetailManagerWorkAreaJPanel;
//import userinterface.RetailManagerRole.ViewCustomerDetailsJPanel;

/**
 *
 * @author jaini
 */
public class FinancialAdvisorWorkAreaJPanel extends javax.swing.JPanel {
JPanel userProcessContainer;
private UserAccount account;
private Organization organization;
private EcoSystem business;
private RetailOrganization retailOrganization;
private Enterprise enterprise;
    /**
     * Creates new form FinancialAdvisorWorkAreaJPanel
     */
    public FinancialAdvisorWorkAreaJPanel(JPanel userProcessContainer,UserAccount account,Organization organization,EcoSystem business,Enterprise enterprise) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.account=account;
        this.retailOrganization=(RetailOrganization)organization;
        this.business=business;
        this.enterprise=enterprise;
        populateTable();
        //enableButton();
         txtmessage.setVisible(false);
         lblaccess.setVisible(false);
         lblreason.setVisible(false);
         
       
       
         btnrequestAccess.setVisible(false);
    }
     public void populateTable(){
        DefaultTableModel model = (DefaultTableModel)workRequestJTable.getModel();
        
        model.setRowCount(0);
        
        for(WorkRequest request : retailOrganization.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[4];
            row[0] = request;
            row[1] = request.getSender().getPerson().getFullName();
            row[2] = request.getReceiver() == null ? null : request.getReceiver().getPerson().getFullName();
            row[3] = request.getStatus();
            model.addRow(row);
            
            
            
        }
     }
//     public void enableButton()
//     {
//         int selectedRow = workRequestJTable.getSelectedRow();
//
//        if (selectedRow < 0){
//            return;
//        }
//        else
//        {
//           Create_Loan_Mortgage_Soc_WorkRequest request = (Create_Loan_Mortgage_Soc_WorkRequest)workRequestJTable.getValueAt(selectedRow, 0);
//           if(request.getSocFlag()==1&& request.getManagerFlag()==1)
//           { 
//             btncustomerDirectory.setEnabled(true);
//           }
//           else
//           {
//               
//             btncustomerDirectory.setEnabled(false);
//           }
//        }
//    }
         
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        processJButton = new javax.swing.JButton();
        valueLabel = new javax.swing.JLabel();
        refreshTestJButton = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        assignJButton = new javax.swing.JButton();
        btnaccess = new javax.swing.JButton();
        txtmessage = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        lblreason = new javax.swing.JLabel();
        lblaccess = new javax.swing.JLabel();
        btncustomerDirectory = new javax.swing.JButton();
        btnrequestAccess = new javax.swing.JButton();

        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Message", "Sender", "Receiver", "Result"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(workRequestJTable);

        processJButton.setText("Process");
        processJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processJButtonActionPerformed(evt);
            }
        });

        valueLabel.setText("<value>");

        refreshTestJButton.setText("Refresh");
        refreshTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshTestJButtonActionPerformed(evt);
            }
        });

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("EnterPrise :");

        assignJButton.setText("Assign to me");
        assignJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignJButtonActionPerformed(evt);
            }
        });

        btnaccess.setText("Access to Customer Directory");
        btnaccess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaccessActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblreason.setText("Reason");

        lblaccess.setText("Access Request");

        btncustomerDirectory.setText("View Customer Directory");
        btncustomerDirectory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncustomerDirectoryActionPerformed(evt);
            }
        });

        btnrequestAccess.setText("RequestAccess");
        btnrequestAccess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrequestAccessActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(174, 174, 174)
                                .addComponent(refreshTestJButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(assignJButton)
                                .addGap(163, 163, 163)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btncustomerDirectory)
                                    .addComponent(processJButton))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnaccess)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnrequestAccess)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblreason)
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtmessage, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblaccess)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnBack)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(refreshTestJButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assignJButton)
                    .addComponent(processJButton))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnaccess)
                    .addComponent(btncustomerDirectory))
                .addGap(18, 18, 18)
                .addComponent(lblaccess)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblreason)
                    .addComponent(txtmessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnrequestAccess)
                .addContainerGap(119, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void processJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processJButtonActionPerformed
        assignJButton.setEnabled(false);
        int selectedRow = workRequestJTable.getSelectedRow();

        if (selectedRow < 0){

            JOptionPane.showMessageDialog(null,"Please select a row");
            return;
        }
        else
        {
        Create_Loan_Mortgage_Soc_WorkRequest request = (Create_Loan_Mortgage_Soc_WorkRequest)workRequestJTable.getValueAt(selectedRow, 0);
         request.setStatus("Processing");
        if(request.getMessage().equalsIgnoreCase("Loan Request"))
        {
            
        System.out.println("Loan");
        

        ProcessLoanRequestJPanel ProcessLoanRequestJPanel = new ProcessLoanRequestJPanel(userProcessContainer, request,enterprise);
        userProcessContainer.add("ProcessLoanRequestJPanel", ProcessLoanRequestJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
              layout.next(userProcessContainer);
        }
        else if(request.getMessage().equalsIgnoreCase("Mortgage Request"))
        {   
             System.out.println("Mortgage");
              ProcessMortgageRequestJPanel ProcessMortgageRequestJPanel = new ProcessMortgageRequestJPanel(userProcessContainer, request,enterprise);
            userProcessContainer.add("ProcessMortgageRequestJPanel", ProcessMortgageRequestJPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
              layout.next(userProcessContainer);
              System.out.println("Status 2"+ request.getStatus());
             
            
        }
    }//GEN-LAST:event_processJButtonActionPerformed
    }
    private void refreshTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshTestJButtonActionPerformed
        
        populateTable();
    }//GEN-LAST:event_refreshTestJButtonActionPerformed

    private void assignJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignJButtonActionPerformed

        int selectedRow = workRequestJTable.getSelectedRow();

        if (selectedRow < 0){
            return;
        }

        WorkRequest request = (WorkRequest)workRequestJTable.getValueAt(selectedRow, 0);
        request.setSender(account);
        request.setStatus("Pending");
        populateTable();
    }//GEN-LAST:event_assignJButtonActionPerformed

    private void btnaccessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaccessActionPerformed
        // TODO add your handling code here:
         
         txtmessage.setVisible(true);
         lblaccess.setVisible(true);
         lblreason.setVisible(true);
         btnrequestAccess.setVisible(true);
         
        
       
            
    }//GEN-LAST:event_btnaccessActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        
userProcessContainer.remove(this);
        CardLayout layout=(CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer); 
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnrequestAccessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrequestAccessActionPerformed
        // TODO add your handling code here:
        btnaccess.setEnabled(true);
        Create_Loan_Mortgage_Soc_WorkRequest request = new Create_Loan_Mortgage_Soc_WorkRequest();
        request.setSocMessage("Access Request");
        request.setMessage(txtmessage.getText().trim());
        request.setEmployeeSender(account);
        request.setStatus("Sent to manager");
        request.setEmployeeFlag(1);
        request.setManagerFlag(0);
        request.setSocFlag(0);
        request.setSender(account);
        
        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof RetailOrganization){
               
                
                {
                org = organization;
                break;
                }
            }
        }
        if (org!=null){
            
            org.getWorkQueue().getWorkRequestList().add(request);
            account.getWorkQueue().getWorkRequestList().add(request);
        }
      
    }//GEN-LAST:event_btnrequestAccessActionPerformed

    private void btncustomerDirectoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncustomerDirectoryActionPerformed
        // TODO add your handling code here:
//         int selectedRow = workRequestJTable.getSelectedRow();
//
//        if (selectedRow < 0){
//            return;
//        }
//        else
//        {
//           Create_Loan_Mortgage_Soc_WorkRequest request = (Create_Loan_Mortgage_Soc_WorkRequest)workRequestJTable.getValueAt(selectedRow, 0);
//           if(request.getSocFlag()==1&& request.getManagerFlag()==1)
//           { 
//        
//               System.out.println("reach");
         ViewCustomerDirectoryAccessJPanel ViewCustomerDirectoryAccessJPanel = new ViewCustomerDirectoryAccessJPanel(userProcessContainer,enterprise,business,account);
         userProcessContainer.add("ViewCustomerDirectoryAccessJPanel", ViewCustomerDirectoryAccessJPanel);
         CardLayout layout = (CardLayout) userProcessContainer.getLayout();
         layout.next(userProcessContainer);
        
       
//           }
//           else
//           {
//               JOptionPane.showMessageDialog(null, "Not authorized");
//           }
//        }
            
        
        
    }//GEN-LAST:event_btncustomerDirectoryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignJButton;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnaccess;
    private javax.swing.JButton btncustomerDirectory;
    private javax.swing.JButton btnrequestAccess;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblaccess;
    private javax.swing.JLabel lblreason;
    private javax.swing.JButton processJButton;
    private javax.swing.JButton refreshTestJButton;
    private javax.swing.JTextField txtmessage;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
