/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.FinancialAdvisorRole;

import Business.Customer.Customer;
import Business.Customer.CustomerAccount;
import Business.Enterprise.Enterprise;
import Business.WorkQueue.Create_Loan_Mortgage_Soc_WorkRequest;
import UserInterface.DoctorRole.RequestLabTestJPanel;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userinterface.CustomerRole.RequestLoanJPanel;

/**
 *
 * @author jaini
 */

public class ProcessLoanRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProcessLoanRequestJPanel
     */
    JPanel userProcessContainer;
   Create_Loan_Mortgage_Soc_WorkRequest request;
   private Enterprise enterprise;
    public ProcessLoanRequestJPanel(JPanel userProcessContaner,Create_Loan_Mortgage_Soc_WorkRequest request,Enterprise enterprise) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.request=request;
        this.enterprise=enterprise;
        txtamount.setText(String.valueOf(request.getPrincipalAmount()));
        txtInterest.setText(String.valueOf(request.getInterestRate()));
        txtSchool.setText(request.getLoanType());
        txtcalculatedAmount.setText(String.valueOf(request.getMonthlyPayment()));
        txtcollateralType.setText(request.getCollateralType());
        txtcollateralValue.setText(String.valueOf(request.getCollateralValue()));
        txtcollegeLoan.setText(String.valueOf(request.getLoanType()));
        txttime.setText(String.valueOf(request.getLoanTerm()));
       // txtmessage.setText(request.getMessage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtamount = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSchool = new javax.swing.JTextField();
        txtcollegeLoan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtInterest = new javax.swing.JTextField();
        txttime = new javax.swing.JTextField();
        txtcalculatedAmount = new javax.swing.JTextField();
        btnCalculate = new javax.swing.JButton();
        btnProcess = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtcollateralType = new javax.swing.JTextField();
        txtcollateralValue = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtmessage = new javax.swing.JTextField();

        jLabel1.setText("Process Loan");

        jLabel2.setText("Amount Required");

        jLabel4.setText("School Loan Required");

        jLabel5.setText("College Loan required");

        jLabel6.setText("Interest Rate offered");

        jLabel7.setText("Time frame for repaymant");

        jLabel8.setText("Calculated Amount (Monthly)");

        btnCalculate.setText("Calculate");

        btnProcess.setText("Process");
        btnProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel9.setText("Collateral Type");

        jLabel10.setText("Collateral Value");

        txtcollateralType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcollateralTypeActionPerformed(evt);
            }
        });

        jLabel11.setText("Message");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(193, 193, 193)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel2)
                        .addGap(137, 137, 137)
                        .addComponent(txtamount, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel4)
                        .addGap(117, 117, 117)
                        .addComponent(txtSchool, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel5)
                        .addGap(116, 116, 116)
                        .addComponent(txtcollegeLoan, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel6)
                        .addGap(116, 116, 116)
                        .addComponent(txtInterest, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel7)
                        .addGap(95, 95, 95)
                        .addComponent(txttime, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel9)
                        .addGap(148, 148, 148)
                        .addComponent(txtcollateralType, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel10)
                        .addGap(146, 146, 146)
                        .addComponent(txtcollateralValue, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(btnProcess))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(178, 178, 178)
                                .addComponent(txtmessage, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80)
                                .addComponent(txtcalculatedAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30)
                        .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel1)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtamount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtSchool, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtcollegeLoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtInterest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txttime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(txtcollateralType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(txtcollateralValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txtcalculatedAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalculate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(txtmessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(btnProcess)
                .addContainerGap(138, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtcollateralTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcollateralTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcollateralTypeActionPerformed

    private void btnProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessActionPerformed
        // TODO add your handling code here:
        Double collateral=Double.parseDouble(txtcollateralValue.getText());
        Double amount=Double.parseDouble(txtamount.getText());
        Double newAmount;
        System.out.println("Part1");
        
        System.out.println("Part1");
        for(Customer c: enterprise.getCustomerDirectory().getCustomerList() )
        {  
            if(request.getId()==(c.getId()))
            {   
                for(CustomerAccount ca: c.getCustomerAccountDirectory().getCustomerAccountList())
                {
                if(request.getLoanType().equalsIgnoreCase("School"))
                   
                     { 
                    
                    c.getCustomerLoanDirectory().createCustomerLoan(c);
                    newAmount=ca.getSavingsMoney()+amount;
                    System.out.println("newAmount"+newAmount);
                    ca.setSavingsMoney(newAmount);
                    System.out.println("newAmount1"+ca.getSavingsMoney());
                     JOptionPane.showMessageDialog(null, "Loan processed");
                    
                
                    }
                    else if(request.getLoanType().equalsIgnoreCase("College"))
                    { 
                    
                       if(ca.getSavingsMoney()+collateral>amount)
                         { System.out.println("Savings"+ca.getSavingsMoney());
                            c.getCustomerLoanDirectory().createCustomerLoan(c);
                            newAmount=ca.getSavingsMoney()+amount;
                            System.out.println("newAmount"+newAmount);
                            ca.setSavingsMoney(newAmount);
                            System.out.println("newAmount1"+ca.getSavingsMoney());
                             JOptionPane.showMessageDialog(null, "Loan processed");
                         } 
                    
                            }
                else
                    {
                        JOptionPane.showMessageDialog(null, "Loan cannot be processed");
                            }  
                
                }
        
        
        request.setMessage(txtmessage.getText());
        request.setStatus("Completed");
       
       }     }    

    }//GEN-LAST:event_btnProcessActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
     userProcessContainer.remove(this);
        CardLayout layout=(CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
                // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnProcess;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtInterest;
    private javax.swing.JTextField txtSchool;
    private javax.swing.JTextField txtamount;
    private javax.swing.JTextField txtcalculatedAmount;
    private javax.swing.JTextField txtcollateralType;
    private javax.swing.JTextField txtcollateralValue;
    private javax.swing.JTextField txtcollegeLoan;
    private javax.swing.JTextField txtmessage;
    private javax.swing.JTextField txttime;
    // End of variables declaration//GEN-END:variables
}
