/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CustomerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.RetailOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.Create_Loan_Mortgage_Soc_WorkRequest;
import UserInterface.DoctorRole.DoctorWorkAreaJPanel;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 *
 * @author jaini
 */
public class CreateAccountJPanel extends javax.swing.JPanel {
JPanel userProcessContainer;
Enterprise enterprise;
EcoSystem business;
UserAccount account;
    /**
     * Creates new form CreateAccountJPanel
     */
    public CreateAccountJPanel(JPanel userProcessContainer,Enterprise enterprise,EcoSystem business,UserAccount account) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.business=business;
        this.enterprise=enterprise;
        
        String fullName=account.getPerson().getFullName();
        String ssn=String.valueOf(account.getPerson().getSocialSecurityNumber());
        String number=String.valueOf(account.getPerson().getPhoneNumber());
        String address=account.getPerson().getAddress();
        String zip=String.valueOf(account.getPerson().getZipCode());
        Date date =account.getPerson().getDateOfBirth();
        SimpleDateFormat format = new SimpleDateFormat("yyyy/MM/dd");
        String dob=format.format(date);
        
        txtAddress.setText(address);
        txtdob.setText(dob);
        txtname.setText(fullName);
        txtphone.setText(number);
        txtssn.setText(ssn);
        txtzip.setText(zip);
        
       
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblmoney = new javax.swing.JLabel();
        btnrequest = new javax.swing.JButton();
        txtname = new javax.swing.JTextField();
        txtssn = new javax.swing.JTextField();
        txtphone = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtzip = new javax.swing.JTextField();
        txtdob = new javax.swing.JTextField();
        txtcheckinMoney = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtcard = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtsavingsMoney = new javax.swing.JTextField();
        CheckinjCheckBox2 = new javax.swing.JCheckBox();
        SavingsjCheckBox1 = new javax.swing.JCheckBox();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Create Account");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        lblName.setText("Name");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, -1));

        jLabel3.setText("Social Security Number");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, -1));

        jLabel4.setText("Phone Number");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));

        jLabel5.setText("Address");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, -1));

        jLabel6.setText("Zip Code");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, -1, -1));

        jLabel7.setText("Date Of Birth");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        lblmoney.setText("Money Deposited in Checkin Account");
        add(lblmoney, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));

        btnrequest.setText("Request Creation of Account");
        btnrequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrequestActionPerformed(evt);
            }
        });
        add(btnrequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, -1, -1));
        add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 60, -1));
        add(txtssn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 60, -1));
        add(txtphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 60, -1));

        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });
        add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 60, -1));
        add(txtzip, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 60, -1));
        add(txtdob, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 60, -1));

        txtcheckinMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcheckinMoneyActionPerformed(evt);
            }
        });
        add(txtcheckinMoney, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 60, -1));

        jLabel2.setText("Debit Card");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, -1, -1));

        txtcard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcardActionPerformed(evt);
            }
        });
        add(txtcard, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 60, -1));

        jLabel8.setText("Money Deposited in Savings Account");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, -1, -1));

        txtsavingsMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsavingsMoneyActionPerformed(evt);
            }
        });
        add(txtsavingsMoney, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 60, -1));

        CheckinjCheckBox2.setText("Checkin Account Required");
        add(CheckinjCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, -1, 40));

        SavingsjCheckBox1.setText("Savings Account Required");
        add(SavingsjCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, -1, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void btnrequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrequestActionPerformed
        if(txtAddress.getText().isEmpty()|| txtcard.getText().isEmpty()||txtdob.getText().isEmpty()||
                txtphone.getText().isEmpty()|| txtssn.getText().isEmpty()||txtzip.getText().isEmpty()
                ||txtcheckinMoney.getText().isEmpty()||txtsavingsMoney.getText().isEmpty()
                ||txtname.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Please enter all fields");
        }
        else
        {
           
        Create_Loan_Mortgage_Soc_WorkRequest request = new Create_Loan_Mortgage_Soc_WorkRequest();
        SimpleDateFormat format = new SimpleDateFormat("yyyy/MM/dd");
        String date = txtdob.getText();
         java.util.Date utilDate = null;
        try {
        utilDate = format.parse(date);
        } catch (ParseException e) {
      // TODO Auto-generated catch block
         e.printStackTrace();
        }
        try{
        String message="Create Account Request";
        request.setMessage(message);
        request.setSender(account);
        request.setStatus("Sent");
        request.setCustomerName(txtname.getText());
        request.setDob(utilDate);
        request.setNumber(Long.parseLong(txtphone.getText()));
        request.setSsn(Long.parseLong(txtphone.getText()));
        request.setZip(Integer.parseInt(txtzip.getText()));
        request.setRequestDate(new Date());
        request.setCheckinMoney(Double.parseDouble((txtcheckinMoney.getText())));
        request.setSavingsMoney(Double.parseDouble((txtsavingsMoney.getText())));
        request.setIsCheckin(CheckinjCheckBox2.getText());
        System.out.println("Hi"+CheckinjCheckBox2.getText());
        request.setIsSavings(SavingsjCheckBox1.getText());
            System.out.println(SavingsjCheckBox1.getText()+"Savings");
        request.setDebit(txtcard.getText());
        request.setAddress(txtAddress.getText());
        
        
        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof RetailOrganization){
                org = organization;
                break;
            }
        }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
            account.getWorkQueue().getWorkRequestList().add(request);
            JOptionPane.showMessageDialog(null, "Request Generated");
        }
        
        }
catch(Exception e) 
{
    JOptionPane.showMessageDialog(null, "Number Format Exception");
}// TODO add your handling code here:
        }      
    }//GEN-LAST:event_btnrequestActionPerformed

    private void txtcardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcardActionPerformed

    private void txtsavingsMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsavingsMoneyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsavingsMoneyActionPerformed

    private void txtcheckinMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcheckinMoneyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcheckinMoneyActionPerformed

        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckinjCheckBox2;
    private javax.swing.JCheckBox SavingsjCheckBox1;
    private javax.swing.JButton btnrequest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblmoney;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtcard;
    private javax.swing.JTextField txtcheckinMoney;
    private javax.swing.JTextField txtdob;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtphone;
    private javax.swing.JTextField txtsavingsMoney;
    private javax.swing.JTextField txtssn;
    private javax.swing.JTextField txtzip;
    // End of variables declaration//GEN-END:variables
}
