/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CustomerRole;

import Business.Customer.Customer;
import Business.Customer.CustomerAccount;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.RetailOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.Create_Loan_Mortgage_Soc_WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author jaini
 */
public class RequestLoanJPanel extends javax.swing.JPanel {
JPanel userProcessContainer;
Enterprise enterprise;
EcoSystem business;
UserAccount account;
    /**
     * Creates new form RequestLoanJPanel
     */
    public RequestLoanJPanel(JPanel userProcessContainer,Enterprise enterprise,EcoSystem business,UserAccount account) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.enterprise=enterprise;
        this.business=business;
        this.account=account;
        valueLabel.setText(enterprise.getName());
        txtmessage.setText("Loan Request");
        
        
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtamount = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSchool = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtInterest = new javax.swing.JTextField();
        txttime = new javax.swing.JTextField();
        txtcalculatedAmount = new javax.swing.JTextField();
        btnCalculate = new javax.swing.JButton();
        btnRequest = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtcollateralType = new javax.swing.JTextField();
        txtcollateralValue = new javax.swing.JTextField();
        valueLabel = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtmessage = new javax.swing.JTextField();
        btninterest = new javax.swing.JButton();
        btnTime = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Request Loan");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 22, -1, -1));

        jLabel2.setText("Amount Required");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, -1, -1));
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 134, -1, -1));
        add(txtamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 60, -1));

        jLabel4.setText("School/College Loan Required");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, -1));

        txtSchool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSchoolActionPerformed(evt);
            }
        });
        add(txtSchool, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 60, -1));

        jLabel6.setText("Interest Rate offered");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, -1, -1));

        jLabel7.setText("Time frame for repaymant");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, -1));

        jLabel8.setText("Calculated Amount (Monthly)");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 140, -1));

        txtInterest.setEditable(false);
        txtInterest.setEnabled(false);
        add(txtInterest, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 60, -1));

        txttime.setEditable(false);
        txttime.setEnabled(false);
        add(txttime, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 60, -1));
        add(txtcalculatedAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 60, -1));

        btnCalculate.setText("Calculate");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });
        add(btnCalculate, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 280, 80, -1));

        btnRequest.setText("Request");
        btnRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestActionPerformed(evt);
            }
        });
        add(btnRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, -1, -1));

        jLabel9.setText("Collateral Type");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, -1, -1));

        jLabel10.setText("Collateral Value");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, -1, -1));

        txtcollateralType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcollateralTypeActionPerformed(evt);
            }
        });
        add(txtcollateralType, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 60, -1));
        add(txtcollateralValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 60, -1));

        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 130, -1));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("EnterPrise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 120, 30));

        jLabel11.setText("Message");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, -1, -1));
        add(txtmessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 60, -1));

        btninterest.setText("Get current Interest Rate");
        btninterest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninterestActionPerformed(evt);
            }
        });
        add(btninterest, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 170, -1));

        btnTime.setText("Get Time Frame");
        btnTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimeActionPerformed(evt);
            }
        });
        add(btnTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, 160, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtcollateralTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcollateralTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcollateralTypeActionPerformed

    private void btnRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestActionPerformed
        // TODO add your handling code here:
             
        Create_Loan_Mortgage_Soc_WorkRequest request = new Create_Loan_Mortgage_Soc_WorkRequest();
        request.setMessage(txtmessage.getText());
        request.setSender(account);
        request.setStatus("Sent");
        request.setPrincipalAmount(Double.parseDouble(txtamount.getText()));
        request.setInterestRate(Double.parseDouble(txtInterest.getText()));
        request.setCollateralType(txtcollateralType.getText());
        request.setCollateralValue(Double.parseDouble(txtcollateralValue.getText()));
        request.setLoanTerm(Double.parseDouble(txttime.getText()));
        request.setId((account.getPerson().getId()));
        
        request.setLoanType(txtSchool.getText());
         
       
        request.setMonthlyPayment(Double.parseDouble(txtcalculatedAmount.getText()));
        
        
        
        
        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof RetailOrganization){
                org = organization;
                break;
            }
        }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
            account.getWorkQueue().getWorkRequestList().add(request);
        }
    }//GEN-LAST:event_btnRequestActionPerformed

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        // TODO add your handling code here:
        Double principalAmount=Double.parseDouble(txtamount.getText());
        Double collateralValue=Double.parseDouble(txtcollateralValue.getText());
        System.out.println("collateral"+collateralValue);
       Double interest= Double.parseDouble(txtInterest.getText());
       //Double collateral=Double.parseDouble(txtcollateralValue.getText());
       Double loanTerm=Double.parseDouble(txttime.getText());
        
        for(Customer c: enterprise.getCustomerDirectory().getCustomerList() )
        {    System.out.println("requestId"+account.getPerson().getId());
                System.out.println("CustId"+c.getId());
            if(account.getPerson().getId()==c.getId())
            {       
                    System.out.println("Entered !!");
                System.out.println("requestId1"+account.getPerson().getId());
                System.out.println("CustId1"+c.getId());
                if(txtSchool.getText().equalsIgnoreCase("School"))
               {
                    loanTerm=5.0;
                    interest=0.068;
                    double interestAmount=(principalAmount*interest*loanTerm/100);
                   double total=interestAmount+principalAmount;
                    double monthlyPayment=total/12;
                    txtcalculatedAmount.setText(String.valueOf(monthlyPayment));
                
               }
                else if(txtSchool.getText().equalsIgnoreCase("College"))
                {
                // c.getCustomerLoan().calculateCollegeCustomerLoan(c, principalAmount,collateralValue);
                    for(CustomerAccount ca: c.getCustomerAccountDirectory().getCustomerAccountList())
                    if(ca.getSavingsMoney()+collateralValue>principalAmount)
                    {
                     System.out.println("SavingsAccount:"+ca.getSavingsMoney());
                  System.out.println("collateral value"+collateralValue);
                    loanTerm=5.0;
                    interest=0.068;
                    double interestAmount=(principalAmount*interest*loanTerm/100);
                    Double total=interestAmount+principalAmount;
                    double monthlyPayment1=total/12;
                    txtcalculatedAmount.setText(String.valueOf(monthlyPayment1));
                    
                   
              }
                    else
                    {
                       JOptionPane.showMessageDialog(null,"Cannot offer without collateral value"); 
                    }
                }
                else
                {
                JOptionPane.showMessageDialog(null,"We offer only school or college loans");
                }
        
        
                
            }    }
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void btninterestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninterestActionPerformed
        // TODO add your handling code here:
        if(txtSchool.getText().equalsIgnoreCase("School"))
        {
          
           txtInterest.setText(String.valueOf(0.068));           
        }
        else if(txtSchool.getText().equalsIgnoreCase("College"))
        {
          
           txtInterest.setText(String.valueOf(0.068));     
        }
        else
        {
            JOptionPane.showMessageDialog(null,"We offer only school or college loans");
        }
    }//GEN-LAST:event_btninterestActionPerformed

    private void btnTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimeActionPerformed
        // TODO add your handling code here:
        if(txtSchool.getText().equalsIgnoreCase("School"))
        {
          
           txttime.setText(String.valueOf(5));           
        }
        else if(txtSchool.getText().equalsIgnoreCase("College"))
        {
          
           txttime.setText(String.valueOf(5));  
        }
        else
        {
            JOptionPane.showMessageDialog(null,"We offer only school or college loans");
        }
        
    }//GEN-LAST:event_btnTimeActionPerformed

    private void txtSchoolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSchoolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSchoolActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnRequest;
    private javax.swing.JButton btnTime;
    private javax.swing.JButton btninterest;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtInterest;
    private javax.swing.JTextField txtSchool;
    private javax.swing.JTextField txtamount;
    private javax.swing.JTextField txtcalculatedAmount;
    private javax.swing.JTextField txtcollateralType;
    private javax.swing.JTextField txtcollateralValue;
    private javax.swing.JTextField txtmessage;
    private javax.swing.JTextField txttime;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
