/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.RetailManagerRole;

import Business.Customer.Customer;
import Business.Customer.CustomerAccount;
import Business.Enterprise.Enterprise;
import Business.WorkQueue.Create_Loan_Mortgage_Soc_WorkRequest;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author jaini
 */

 
public class ProcessCreateAccountWorkRequestJPanel extends javax.swing.JPanel {
JPanel userProcessContainer;
    Create_Loan_Mortgage_Soc_WorkRequest request;
    Enterprise enterprise;

    /**
     * Creates new form ProcessCreateAccountWorkRequestJPanel
     */
    public ProcessCreateAccountWorkRequestJPanel(JPanel userProcessContainer,Create_Loan_Mortgage_Soc_WorkRequest request,Enterprise enterprise) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.request=request;
        this.enterprise=enterprise;
        txtFullName.setText(request.getCustomerName());
        
        
        txtAddress.setText(request.getAddress());
        txtcard.setText(request.getDebit());
        txtphone.setText(String.valueOf(request.getNumber()));
        txtssn.setText(String.valueOf(request.getSsn()));
        txtzip.setText(String.valueOf(request.getZip()));
        txtcheckinMoney.setText(String.valueOf(request.getCheckinMoney()));
        txtsavingsMoney.setText(String.valueOf(request.getSavingsMoney()));
        CheckinjCheckBox2.setText(request.getIsCheckin());
        SavingsjCheckBox1.setText(request.getIsSavings());
        System.out.println("Status"+request.getIsCheckin());
        System.out.println("Status1"+request.getIsSavings());
        if(request.getIsCheckin().equals("Checkin Account Required")&& request.getIsSavings().equals("Savings Account Required"))
        {
            CheckinjCheckBox2.setSelected(true);
            SavingsjCheckBox1.setSelected(true);
            System.out.println("both");
            
        }
        else if(request.getIsCheckin().equals("Checkin Account Required"))
        {
            CheckinjCheckBox2.setSelected(true);
            
        }
        else if(request.getIsSavings().equals("Savings Account Required"))
        {   System.out.println("Part2"+request.getIsSavings());
            SavingsjCheckBox1.setSelected(true);
        }
        
       // CheckinjCheckBox2.setText(request.getIsCheckin());
        //SavingsjCheckBox1.setText(request.getIsSavings());
        txtmessage.setText(request.getMessage());
 SimpleDateFormat s=new SimpleDateFormat("MM/dd/yyyy");
       Date date1=request.getDob();
       String date2=s.format(date1);
        
        txtdob.setText(date2);
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtFullName = new javax.swing.JTextField();
        txtmessage = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        submitJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblmoney = new javax.swing.JLabel();
        txtssn = new javax.swing.JTextField();
        txtphone = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtzip = new javax.swing.JTextField();
        txtdob = new javax.swing.JTextField();
        txtcheckinMoney = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtcard = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtsavingsMoney = new javax.swing.JTextField();
        SavingsjCheckBox1 = new javax.swing.JCheckBox();
        CheckinjCheckBox2 = new javax.swing.JCheckBox();

        jLabel1.setText("Customer Name");

        txtFullName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFullNameActionPerformed(evt);
            }
        });

        txtmessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmessageActionPerformed(evt);
            }
        });

        jLabel2.setText("Message");

        submitJButton.setText("Submit Result");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });

        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Social Security Number");

        jLabel4.setText("Phone Number");

        jLabel5.setText("Address");

        jLabel6.setText("Zip Code");

        jLabel7.setText("Date Of Birth");

        lblmoney.setText("Money Deposited in Checkin Account");

        txtphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtphoneActionPerformed(evt);
            }
        });

        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });

        txtdob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdobActionPerformed(evt);
            }
        });

        txtcheckinMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcheckinMoneyActionPerformed(evt);
            }
        });

        jLabel8.setText("Debit Card");

        txtcard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcardActionPerformed(evt);
            }
        });

        jLabel9.setText("Money Deposited in Savings Account");

        txtsavingsMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsavingsMoneyActionPerformed(evt);
            }
        });

        SavingsjCheckBox1.setText("Savings Account Required");

        CheckinjCheckBox2.setText("Checkin Account Required");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(lblmoney)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8)))
                            .addComponent(SavingsjCheckBox1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtFullName, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                                    .addComponent(txtmessage, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                                    .addComponent(txtssn)
                                    .addComponent(txtphone)
                                    .addComponent(txtAddress)
                                    .addComponent(txtzip)
                                    .addComponent(txtdob)
                                    .addComponent(txtcheckinMoney)
                                    .addComponent(txtsavingsMoney)
                                    .addComponent(txtcard)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(CheckinjCheckBox2))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backJButton)
                        .addGap(45, 45, 45)
                        .addComponent(submitJButton)))
                .addContainerGap(189, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtssn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtzip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtdob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblmoney)
                    .addComponent(txtcheckinMoney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtsavingsMoney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtcard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SavingsjCheckBox1)
                    .addComponent(CheckinjCheckBox2))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backJButton)
                    .addComponent(submitJButton))
                .addContainerGap(85, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtFullNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFullNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFullNameActionPerformed

    private void txtmessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmessageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmessageActionPerformed

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
        for(Customer c: enterprise.getCustomerDirectory().getCustomerList())
        {    
            if(request.getCustomerName().equalsIgnoreCase(c.getFullName()))
            {
                System.out.println("Hello");
                 System.out.println("customer:"+enterprise.getCustomerDirectory().getCustomerList());
                
                
                if(CheckinjCheckBox2.isSelected()==true&& SavingsjCheckBox1.isSelected()==true)
                {
                   CustomerAccount ca= c.getCustomerAccountDirectory().createCustomerAccount(c);
       
                    ca.setAccountType("Checkin and Savings Account");
                    ca.setType("CS");
                    System.out.println("customerAccount"+ca.getAccountType());
                    ca.setSavingsMoney(request.getSavingsMoney());
                    ca.setCheckinMoney(request.getCheckinMoney());
                    System.err.println("Both");
                  
                    System.out.println("CREATED2");
                    if(request.getDebit().equalsIgnoreCase("Yes"))
                        {   ca.setHasDebitCard(txtcard.getText());
                           c.getCustomerAccountDirectory().generateDebitDetails(ca);
                            System.out.println("DETAIL:"+ca.getDebitCardNumber()+ca.getValidThrough()+ca.getCvv());
                        }
                    
                }
                else if(SavingsjCheckBox1.isSelected()==true)
                {
                    CustomerAccount ca1= c.getCustomerAccountDirectory().createCustomerAccount(c);
                    ca1.setAccountType("Savings Account");
                    ca1.setType("S");
                    System.out.println("customerAccount"+ca1.getAccountType());
                    ca1.setSavingsMoney(request.getSavingsMoney());
                    c.getCustomerAccountDirectory().getCustomerAccountList().add(ca1);
                    System.out.println("CREATED1");
                }
                
                else if(CheckinjCheckBox2.isSelected()==true)
                {   CustomerAccount ca2= c.getCustomerAccountDirectory().createCustomerAccount(c);
                    
                    ca2.setAccountType("Checkin Account");
                    ca2.setType("C");
                    System.out.println("customerAccount"+ca2.getAccountType());
                    ca2.setCheckinMoney(request.getCheckinMoney());
                    
                    c.getCustomerAccountDirectory().getCustomerAccountList().add(ca2);
                    System.out.println("CREATED");
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Please select account type");
                }
                
        c.setAddress(txtAddress.getText());     
        c.setPhoneNumber((request.getNumber()));
        c.setSocialSecurityNumber((request.getSsn()));
        c.setZipCode((request.getZip()));
        c.setDateOfBirth(request.getDob());
        
        
        
                
                
                
            }
            
            
        }
        request.setMessage(txtmessage.getText());
        request.setStatus("Completed");
       
        
    }//GEN-LAST:event_submitJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout=(CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer); 
    }//GEN-LAST:event_backJButtonActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void txtcheckinMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcheckinMoneyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcheckinMoneyActionPerformed

    private void txtcardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcardActionPerformed

    private void txtsavingsMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsavingsMoneyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsavingsMoneyActionPerformed

    private void txtphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtphoneActionPerformed

    private void txtdobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdobActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckinjCheckBox2;
    private javax.swing.JCheckBox SavingsjCheckBox1;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblmoney;
    private javax.swing.JButton submitJButton;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtcard;
    private javax.swing.JTextField txtcheckinMoney;
    private javax.swing.JTextField txtdob;
    private javax.swing.JTextField txtmessage;
    private javax.swing.JTextField txtphone;
    private javax.swing.JTextField txtsavingsMoney;
    private javax.swing.JTextField txtssn;
    private javax.swing.JTextField txtzip;
    // End of variables declaration//GEN-END:variables
}
