/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.RetailManagerRole;

import Business.Customer.Customer;
import Business.Customer.CustomerAccount;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Person.Person;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JPanel;

/**
 *
 * @author jaini
 */
public class ViewCustomerDetailsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewCustomerDetailsJPanel
     */
    JPanel userProcessContainer;
    private Enterprise enterprise;
    private EcoSystem business;
    private Customer c;
   // private Person p;
    public ViewCustomerDetailsJPanel(JPanel userProcessContainer, Enterprise enterprise,EcoSystem business,Customer c) {
        initComponents();
        
        this.business=business;
        this.userProcessContainer=userProcessContainer;
        this.enterprise=enterprise;
        this.c=c;
       
        txtname.setText(c.getFullName());
        Date date =c.getDateOfBirth();
        
        SimpleDateFormat format = new SimpleDateFormat("yyyy/MM/dd");
        String dob=format.format(date);
        System.out.println("Final dob:"+dob);
        txtdob.setText(dob);
        
        for(CustomerAccount ca: c.getCustomerAccountDirectory().getCustomerAccountList())
        {   System.out.println("There"+ca.getCheckinMoney());
            txtcheckinMoney.setText(String.valueOf(ca.getCheckinMoney()));
            txtsavingsMoney.setText(String.valueOf(ca.getSavingsMoney()));
            txtcard.setText(ca.isHasDebitCard());
            
            
            if(ca.getAccountType().equals("Checkin Account"))
        {
            CheckinjCheckBox2.setSelected(true);
        }
        else if(ca.getAccountType().equals("Savings Account"))
        {
            SavingsjCheckBox1.setSelected(true);
        }
        else if(ca.getAccountType().equals("Checkin and Savings Account"))
        {
            CheckinjCheckBox2.setSelected(true);
            SavingsjCheckBox1.setSelected(true);
        }
        }
        
        txtAddress.setText(c.getAddress());
       // txtcard.setText(c.getCustomerAccountDirectory().);
        txtphone.setText(String.valueOf(c.getPhoneNumber()));
        txtssn.setText(String.valueOf(c.getSocialSecurityNumber()));
        txtzip.setText(String.valueOf(c.getZipCode()));
      
        //txtcheckinMoney.setText(String.valueOf(request.getCheckinMoney()));
        //txtsavingsMoney.setText(String.valueOf(request.getSavingsMoney()));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblmoney = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtssn = new javax.swing.JTextField();
        txtphone = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtzip = new javax.swing.JTextField();
        txtdob = new javax.swing.JTextField();
        txtcheckinMoney = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtcard = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtsavingsMoney = new javax.swing.JTextField();
        CheckinjCheckBox2 = new javax.swing.JCheckBox();
        SavingsjCheckBox1 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblName.setText("Name");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, -1, -1));

        jLabel3.setText("Social Security Number");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, -1, -1));

        jLabel4.setText("Phone Number");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, -1, -1));

        jLabel5.setText("Address");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, -1, -1));

        jLabel6.setText("Zip Code");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, -1, -1));

        jLabel7.setText("Date Of Birth");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, -1, -1));

        lblmoney.setText("Money Deposited in Checkin Account");
        add(lblmoney, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, -1, -1));

        txtname.setEditable(false);
        txtname.setEnabled(false);
        add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 60, -1));

        txtssn.setEditable(false);
        txtssn.setEnabled(false);
        add(txtssn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 60, -1));

        txtphone.setEditable(false);
        txtphone.setEnabled(false);
        add(txtphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 60, -1));

        txtAddress.setEditable(false);
        txtAddress.setEnabled(false);
        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });
        add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 60, -1));

        txtzip.setEditable(false);
        txtzip.setEnabled(false);
        add(txtzip, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 60, -1));

        txtdob.setEditable(false);
        txtdob.setEnabled(false);
        add(txtdob, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, 60, -1));

        txtcheckinMoney.setEditable(false);
        txtcheckinMoney.setEnabled(false);
        txtcheckinMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcheckinMoneyActionPerformed(evt);
            }
        });
        add(txtcheckinMoney, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 150, -1));

        jLabel2.setText("Debit Card");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, -1, -1));

        txtcard.setEditable(false);
        txtcard.setEnabled(false);
        txtcard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcardActionPerformed(evt);
            }
        });
        add(txtcard, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, 60, -1));

        jLabel8.setText("Money Deposited in Savings Account");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, -1, -1));

        txtsavingsMoney.setEditable(false);
        txtsavingsMoney.setEnabled(false);
        txtsavingsMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsavingsMoneyActionPerformed(evt);
            }
        });
        add(txtsavingsMoney, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 160, -1));

        CheckinjCheckBox2.setText("Checkin Account Required");
        CheckinjCheckBox2.setEnabled(false);
        add(CheckinjCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, -1, 40));

        SavingsjCheckBox1.setText("Savings Account Required");
        SavingsjCheckBox1.setEnabled(false);
        add(SavingsjCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, -1, 40));

        jLabel1.setText("Customer Details");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void txtcheckinMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcheckinMoneyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcheckinMoneyActionPerformed

    private void txtcardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcardActionPerformed

    private void txtsavingsMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsavingsMoneyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsavingsMoneyActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout=(CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckinjCheckBox2;
    private javax.swing.JCheckBox SavingsjCheckBox1;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblmoney;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtcard;
    private javax.swing.JTextField txtcheckinMoney;
    private javax.swing.JTextField txtdob;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtphone;
    private javax.swing.JTextField txtsavingsMoney;
    private javax.swing.JTextField txtssn;
    private javax.swing.JTextField txtzip;
    // End of variables declaration//GEN-END:variables
}
